#version 330
#extension GL_ARB_separate_shader_objects : require

// Generated by scripts/gen_shaders_26_3.py from src/main/resources/.../box_shadow.vsh - do not edit.

// Same uniform blocks as vanilla core/gui.vsh.
layout(std140) uniform DynamicTransforms {
    mat4 ModelViewMat;
    mat4 TextureMat;
    vec4 ColorModulator;
    vec3 ModelOffset;
};
layout(std140) uniform Projection {
    mat4 ProjMat;
};

layout(location = 0) in vec3 Position; // z = shadow offset packed (see ShadowState)
layout(location = 1) in vec4 Color;
layout(location = 2) in vec2 UV0;      // position relative to the box center (GUI px)
layout(location = 3) in ivec2 UV1;     // box half size * 8
layout(location = 4) in ivec2 UV2;     // box radii * 2 packed: x = tl | tr << 8, y = br | bl << 8
layout(location = 5) in float LineWidth; // shadow parameters packed (see ShadowState); negative = inset

layout(location = 0) out vec4 vertexColor;
layout(location = 1) out vec2 localPos;
layout(location = 2) flat out vec2 halfSize;
layout(location = 3) flat out vec4 radii;
layout(location = 4) flat out vec2 offset;
layout(location = 5) flat out float sigma;
layout(location = 6) flat out float grow;
layout(location = 7) flat out float inset;

void main() {
    gl_Position = ProjMat * ModelViewMat * vec4(Position.xy, 0.0, 1.0);
    vertexColor = Color;
    localPos = UV0;
    halfSize = vec2(UV1) / 8.0;
    int a = UV2.x & 0xFFFF;
    int b = UV2.y & 0xFFFF;
    radii = vec4(float(a & 0xFF), float((a >> 8) & 0xFF), float(b & 0xFF), float((b >> 8) & 0xFF)) / 2.0;
    int o = int(Position.z + 0.5);
    offset = vec2(float(o % 2048) - 1024.0, float(o / 2048) - 1024.0) / 4.0;
    inset = LineWidth < 0.0 ? 1.0 : 0.0;
    int p = int(abs(LineWidth) + 0.5) - 1;
    sigma = float(p % 256) / 2.0;
    grow = float(p / 256) / 2.0 - 128.0;
}
