// GENERATED by scripts/gen_tags.py - do not edit by hand.
@file:Suppress("FunctionName", "unused")

package net.sbo.guilib.core.dsl

import net.sbo.guilib.core.dom.Element
import net.sbo.guilib.core.dom.Ref
import net.sbo.guilib.core.event.FocusEvent
import net.sbo.guilib.core.event.InputEvent
import net.sbo.guilib.core.event.KeyboardEvent
import net.sbo.guilib.core.event.MouseEvent
import net.sbo.guilib.core.event.ScrollEvent
import net.sbo.guilib.core.event.UIEvent
import net.sbo.guilib.core.event.WheelEvent

@Suppress("UNCHECKED_CAST")
private fun <E : UIEvent> MutableMap<String, (UIEvent) -> Unit>.on(key: String, handler: ((E) -> Unit)?) {
    if (handler != null) this[key] = handler as (UIEvent) -> Unit
}


/** Generic block container (`display: block`). */
fun NodeBuilder.div(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("div", key, id, className, style, ref, attrs, handlers, children)
}

/** Inline text container (`display: inline`). */
fun NodeBuilder.span(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("span", key, id, className, style, ref, attrs, handlers, children)
}

/** Paragraph (`display: block`). */
fun NodeBuilder.p(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("p", key, id, className, style, ref, attrs, handlers, children)
}

/** Heading. */
fun NodeBuilder.h1(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("h1", key, id, className, style, ref, attrs, handlers, children)
}

/** Heading. */
fun NodeBuilder.h2(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("h2", key, id, className, style, ref, attrs, handlers, children)
}

/** Heading. */
fun NodeBuilder.h3(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("h3", key, id, className, style, ref, attrs, handlers, children)
}

/** Heading. */
fun NodeBuilder.h4(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("h4", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.section(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("section", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.header(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("header", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.footer(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("footer", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.nav(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("nav", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.main(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("main", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.aside(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("aside", key, id, className, style, ref, attrs, handlers, children)
}

/** Block container. */
fun NodeBuilder.article(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("article", key, id, className, style, ref, attrs, handlers, children)
}

/** List (`display: block`, no bullets). */
fun NodeBuilder.ul(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("ul", key, id, className, style, ref, attrs, handlers, children)
}

/** List (`display: block`, no numbers). */
fun NodeBuilder.ol(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("ol", key, id, className, style, ref, attrs, handlers, children)
}

/** List item. */
fun NodeBuilder.li(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("li", key, id, className, style, ref, attrs, handlers, children)
}

/** Inline label; clicking it focuses/toggles the first input inside. */
fun NodeBuilder.label(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("label", key, id, className, style, ref, attrs, handlers, children)
}

/** Inline clickable text (no navigation; use onClick). */
fun NodeBuilder.a(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("a", key, id, className, style, ref, attrs, handlers, children)
}

/** Bold inline text. */
fun NodeBuilder.strong(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("strong", key, id, className, style, ref, attrs, handlers, children)
}

/** Bold inline text. */
fun NodeBuilder.b(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("b", key, id, className, style, ref, attrs, handlers, children)
}

/** Italic inline text. */
fun NodeBuilder.em(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("em", key, id, className, style, ref, attrs, handlers, children)
}

/** Italic inline text. */
fun NodeBuilder.i(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("i", key, id, className, style, ref, attrs, handlers, children)
}

/** Smaller inline text. */
fun NodeBuilder.small(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("small", key, id, className, style, ref, attrs, handlers, children)
}

/** Inline code (Minecraft font). */
fun NodeBuilder.code(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("code", key, id, className, style, ref, attrs, handlers, children)
}

/** Preformatted block (`white-space: pre`). */
fun NodeBuilder.pre(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("pre", key, id, className, style, ref, attrs, handlers, children)
}

/** Scroll container: a div with `overflow: auto` and a styled scrollbar. (Not an HTML tag.) */
fun NodeBuilder.scroll(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("scroll", key, id, className, style, ref, attrs, handlers, children)
}

/** Button (`display: inline-flex`, centered content). Disabled buttons receive no mouse events. */
fun NodeBuilder.button(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    disabled: Boolean = false,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
    children: (NodeBuilder.() -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    if (disabled) attrs["disabled"] = true
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("button", key, id, className, style, ref, attrs, handlers, children)
}

/** Line break inside text. */
fun NodeBuilder.br(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("br", key, id, className, style, ref, attrs, handlers, null)
}

/** Horizontal rule. */
fun NodeBuilder.hr(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("hr", key, id, className, style, ref, attrs, handlers, null)
}

/** Image: `src` is a resource location (`"modid:textures/x.png"`); PNG, SVG and (animated) GIF are supported. */
fun NodeBuilder.img(
    src: String,
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    alt: String? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    attrs["src"] = src
    if (alt != null) attrs["alt"] = alt
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("img", key, id, className, style, ref, attrs, handlers, null)
}

/** Minecraft item icon (16×16 by default). `stack` is a `net.minecraft.world.item.ItemStack`. (Not an HTML tag.) */
fun NodeBuilder.item(
    stack: Any,
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    decorations: Boolean = true,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    attrs["stack"] = stack
    if (decorations) attrs["decorations"] = true
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("item", key, id, className, style, ref, attrs, handlers, null)
}

/** Minecraft entity model (48×72 by default), scaled to fit the box. `entity` is a `net.minecraft.world.entity.LivingEntity`, e.g. `FakePlayer.of("Notch")`. `followMouse` turns it towards the cursor; otherwise it looks at its center offset by `lookX`/`lookY` px. `scale` multiplies the fitted size. (Not an HTML tag.) */
fun NodeBuilder.entity(
    entity: Any,
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    followMouse: Boolean = false,
    lookX: Float = 0f,
    lookY: Float = 0f,
    scale: Float = 1f,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    attrs["entity"] = entity
    if (followMouse) attrs["followmouse"] = true
    attrs["lookx"] = lookX
    attrs["looky"] = lookY
    attrs["scale"] = scale
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("entity", key, id, className, style, ref, attrs, handlers, null)
}

/** Minecraft player face (16×16 by default), like in the tab list. `player` is a name (`String`), a `UUID`, a `GameProfile`, a `ResolvableProfile` or an `AbstractClientPlayer`; the skin loads in the background (default skin until then) and works without a world. `hat = false` hides the hat layer. (Not an HTML tag.) */
fun NodeBuilder.playerHead(
    player: Any,
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    hat: Boolean = true,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    attrs["player"] = player
    if (hat) attrs["hat"] = true
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("player-head", key, id, className, style, ref, attrs, handlers, null)
}

/** Form input. `type`: `text`, `password`, `number`, `checkbox`. Controlled like React: pass `value`/`checked` and update them in `onInput`/`onChange`. */
fun NodeBuilder.input(
    className: String? = null,
    id: String? = null,
    style: String? = null,
    key: Any? = null,
    title: String? = null,
    ref: Ref<Element?>? = null,
    tabIndex: Int? = null,
    type: String = "text",
    value: String? = null,
    placeholder: String? = null,
    checked: Boolean = false,
    disabled: Boolean = false,
    maxLength: Int? = null,
    autoFocus: Boolean = false,
    onInput: ((InputEvent) -> Unit)? = null,
    onChange: ((InputEvent) -> Unit)? = null,
    onClick: ((MouseEvent) -> Unit)? = null,
    onDoubleClick: ((MouseEvent) -> Unit)? = null,
    onContextMenu: ((MouseEvent) -> Unit)? = null,
    onMouseDown: ((MouseEvent) -> Unit)? = null,
    onMouseUp: ((MouseEvent) -> Unit)? = null,
    onMouseMove: ((MouseEvent) -> Unit)? = null,
    onMouseEnter: ((MouseEvent) -> Unit)? = null,
    onMouseLeave: ((MouseEvent) -> Unit)? = null,
    onWheel: ((WheelEvent) -> Unit)? = null,
    onKeyDown: ((KeyboardEvent) -> Unit)? = null,
    onKeyUp: ((KeyboardEvent) -> Unit)? = null,
    onFocus: ((FocusEvent) -> Unit)? = null,
    onBlur: ((FocusEvent) -> Unit)? = null,
    onScroll: ((ScrollEvent) -> Unit)? = null,
) {
    val attrs = HashMap<String, Any?>()
    if (title != null) attrs["title"] = title
    if (tabIndex != null) attrs["tabindex"] = tabIndex
    attrs["type"] = type
    if (value != null) attrs["value"] = value
    if (placeholder != null) attrs["placeholder"] = placeholder
    if (checked) attrs["checked"] = true
    if (disabled) attrs["disabled"] = true
    if (maxLength != null) attrs["maxlength"] = maxLength
    if (autoFocus) attrs["autofocus"] = true
    val handlers = HashMap<String, (UIEvent) -> Unit>()
    handlers.on("input", onInput)
    handlers.on("change", onChange)
    handlers.on("click", onClick)
    handlers.on("dblclick", onDoubleClick)
    handlers.on("contextmenu", onContextMenu)
    handlers.on("mousedown", onMouseDown)
    handlers.on("mouseup", onMouseUp)
    handlers.on("mousemove", onMouseMove)
    handlers.on("mouseenter", onMouseEnter)
    handlers.on("mouseleave", onMouseLeave)
    handlers.on("wheel", onWheel)
    handlers.on("keydown", onKeyDown)
    handlers.on("keyup", onKeyUp)
    handlers.on("focus", onFocus)
    handlers.on("blur", onBlur)
    handlers.on("scroll", onScroll)
    element("input", key, id, className, style, ref, attrs, handlers, null)
}
