#!/usr/bin/env python3
"""Generates the Minecraft 26.3 copies of GuiLib's shaders.

26.3 compiles core shaders to SPIR-V, which needs explicit `layout(location = n)` on every vertex input and
varying, and it reordered vanilla's `DynamicTransforms` uniform block. The shaders in src/main/resources stay
the source of truth (26.1.2 / 26.2); run this script after changing them:

    python scripts/gen_shaders_26_3.py

The output in versions/26.3-fabric/src/main/resources replaces the root copies in the 26.3 jar.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src/main/resources/assets/guilib/shaders/core"
DST = ROOT / "versions/26.3-fabric/src/main/resources/assets/guilib/shaders/core"

OLD_BLOCK = re.compile(r"layout\(std140\) uniform DynamicTransforms \{.*?\};", re.S)
NEW_BLOCK = """layout(std140) uniform DynamicTransforms {
    mat4 ModelViewMat;
    mat4 TextureMat;
    vec4 ColorModulator;
    vec3 ModelOffset;
};"""
# Top-level `in` / `out` declarations, optionally `flat`.
VARYING = re.compile(r"^(flat )?(in|out) ", re.M)


def convert(text: str, name: str) -> str:
    if not text.startswith("#version 330\n"):
        raise SystemExit(f"{name}: expected '#version 330' on the first line")
    text = text.replace(
        "#version 330\n",
        "#version 330\n#extension GL_ARB_separate_shader_objects : require\n\n"
        f"// Generated by scripts/gen_shaders_26_3.py from src/main/resources/.../{name} - do not edit.\n",
        1,
    )
    text, blocks = OLD_BLOCK.subn(NEW_BLOCK, text)
    if blocks != 1:
        raise SystemExit(f"{name}: expected exactly one DynamicTransforms block, found {blocks}")
    counters = {"in": 0, "out": 0}

    def locate(m: re.Match) -> str:
        kind = m.group(2)
        loc = counters[kind]
        counters[kind] += 1
        return f"layout(location = {loc}) {m.group(1) or ''}{kind} "

    return VARYING.sub(locate, text)


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    for src in sorted(SRC.glob("*.[vf]sh")):
        out = convert(src.read_text(encoding="utf-8"), src.name)
        (DST / src.name).write_text(out, encoding="utf-8", newline="\n")
        print(f"wrote {(DST / src.name).relative_to(ROOT)}")


if __name__ == "__main__":
    main()
